services:
  umtx2:
    build: .
    container_name: umtx2
    restart: unless-stopped

    environment:
      HOST_IP: "192.168.11.17"
      AUTO_UPDATE_PAYLOADS: "true"

    ports:
      - "53:53/udp"
      - "443:443"
      - "80:80"
 